[package]
name = "pixelflut"
version = "0.0.1"
authors = ["Raphael Peters <raphael.r.peters@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = """
An unfinished library for encoding and decoding pixelflut messages providing a
simple async protocol interface using tokio.
"""
homepage = "https://github.com/rappet/rust-pixelflut"
repository = "https://github.com/rappet/rust-pixelflut"
keywords = ["pixelflut"]

[features]
default = ["sync"]
sync = ["bufstream"]
async = ["bytes", "futures", "tokio", "tokio-io", "tokio-codec", "tokio-core"]

[[example]]
name = "sync_client"
required-features = ["sync"]

[[example]]
name = "sync_server"
required-features = ["sync"]

[[example]]
name = "async_server"
required-features = ["async"]

[dependencies]
bufstream = { version = "0.1", optional = true }
bytes = { version = "0.4", optional = true }
futures = { version = "0.1", optional = true }
tokio = { version = "0.1", optional = true }
tokio-io = { version = "0.1", optional = true }
tokio-codec = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }
